# Makefile

TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/../../../../generated/DebuggerPacketReceiver.sv
TOPLEVEL = DebuggerPacketReceiver
MODULE = test_DebuggerPacketReceiver

include $(shell cocotb-config --makefiles)/Makefile.sim
