# Makefile

TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/../../../../generated/DebuggerPacketSender.sv
TOPLEVEL = DebuggerPacketSender
MODULE = test_DebuggerPacketSender

include $(shell cocotb-config --makefiles)/Makefile.sim
