/**
 * @file type.h
 * @author M.H. Gholamrezaei (mh@hyperdbg.org)
 *
 * @brief Variable type definitions for the script engine
 * @details
 * @version 0.1
 * @date 2020-10-22
 *
 * @copyright This project is released under the GNU Public License v3.
 *
 */
#pragma once

#ifndef TYPE_H
#    define TYPE_H

typedef enum _VARIABLE_TYPE_KIND
{
    TY_UNKNOWN,
    TY_VOID,
    TY_BOOL,
    TY_CHAR,
    TY_SHORT,
    TY_INT,
    TY_LONG,
    TY_LLONG,
    TY_FLOAT,
    TY_DOUBLE,
    TY_LDOUBLE,
    TY_ENUM,
    TY_PTR,
    TY_FUNC,
    TY_ARRAY,
    TY_VLA, // variable-length array
    TY_STRUCT,
    TY_UNION,
} VARIABLE_TYPE_KIND;

typedef enum _POINTER_PROVENANCE
{
    POINTER_PROVENANCE_UNKNOWN,
    POINTER_PROVENANCE_LOCAL,
    POINTER_PROVENANCE_REMOTE,
} POINTER_PROVENANCE;

typedef enum _INTEGER_TYPE_RANK
{
    INTEGER_RANK_NONE,
    INTEGER_RANK_BOOL,
    INTEGER_RANK_CHAR,
    INTEGER_RANK_SHORT,
    INTEGER_RANK_INT,
    INTEGER_RANK_LONG,
    INTEGER_RANK_LONG_LONG,
} INTEGER_TYPE_RANK;

typedef struct _STRUCT_MEMBER STRUCT_MEMBER, *PSTRUCT_MEMBER;

typedef struct _VARIABLE_TYPE
{
    VARIABLE_TYPE_KIND      Kind;
    int                     Size;  // sizeof() value
    int                     Align; // alignment
    BOOLEAN                 IsUnsigned;
    struct _VARIABLE_TYPE * Base;
    int                     ArrayLen;
    POINTER_PROVENANCE      PointerProvenance;
    char *                  TagName;
    BOOLEAN                 IsComplete;
    PSTRUCT_MEMBER          Members;
    INTEGER_TYPE_RANK       IntegerRank;
} VARIABLE_TYPE, *PVARIABLE_TYPE;

struct _STRUCT_MEMBER
{
    char *                  Name;
    PVARIABLE_TYPE          Type;
    unsigned int            Offset;
    unsigned int            DeclarationOrder;
    PSTRUCT_MEMBER          Next;
};

extern VARIABLE_TYPE * VARIABLE_TYPE_UNKNOWN;

extern VARIABLE_TYPE * VARIABLE_TYPE_VOID;
extern VARIABLE_TYPE * VARIABLE_TYPE_BOOL;

extern VARIABLE_TYPE * VARIABLE_TYPE_CHAR;
extern VARIABLE_TYPE * VARIABLE_TYPE_SHORT;
extern VARIABLE_TYPE * VARIABLE_TYPE_INT;
extern VARIABLE_TYPE * VARIABLE_TYPE_LONG;
extern VARIABLE_TYPE * VARIABLE_TYPE_LLONG;

extern VARIABLE_TYPE * VARIABLE_TYPE_UCHAR;
extern VARIABLE_TYPE * VARIABLE_TYPE_USHORT;
extern VARIABLE_TYPE * VARIABLE_TYPE_UINT;
extern VARIABLE_TYPE * VARIABLE_TYPE_ULONG;
extern VARIABLE_TYPE * VARIABLE_TYPE_ULLONG;

extern VARIABLE_TYPE * VARIABLE_TYPE_FLOAT;
extern VARIABLE_TYPE * VARIABLE_TYPE_DOUBLE;
extern VARIABLE_TYPE * VARIABLE_TYPE_LDOUBLE;

typedef enum _SCRIPT_ENGINE_ERROR_TYPE
{
    SCRIPT_ENGINE_ERROR_FREE,
    SCRIPT_ENGINE_ERROR_SYNTAX,
    SCRIPT_ENGINE_ERROR_UNKNOWN_TOKEN,
    SCRIPT_ENGINE_ERROR_UNRESOLVED_VARIABLE,
    SCRIPT_ENGINE_ERROR_UNHANDLED_SEMANTIC_RULE,
    SCRIPT_ENGINE_ERROR_TEMP_LIST_FULL,
    SCRIPT_ENGINE_ERROR_UNDEFINED_FUNCTION,
    SCRIPT_ENGINE_ERROR_UNDEFINED_VARIABLE_TYPE,
    SCRIPT_ENGINE_ERROR_VOID_FUNCTION_RETURNING_VALUE,
    SCRIPT_ENGINE_ERROR_NON_VOID_FUNCTION_NOT_RETURNING_VALUE,
    SCRIPT_ENGINE_ERROR_UNKNOWN_STRUCT_TAG,
    SCRIPT_ENGINE_ERROR_INCOMPLETE_TYPE,
    SCRIPT_ENGINE_ERROR_DUPLICATE_STRUCT_DEFINITION,
    SCRIPT_ENGINE_ERROR_DUPLICATE_STRUCT_MEMBER,
    SCRIPT_ENGINE_ERROR_DUPLICATE_TYPEDEF,
    SCRIPT_ENGINE_ERROR_INVALID_ARRAY_SIZE,
    SCRIPT_ENGINE_ERROR_INVALID_FLOAT_LITERAL,
    SCRIPT_ENGINE_ERROR_FLOAT_OUT_OF_RANGE,
    SCRIPT_ENGINE_ERROR_UNSUPPORTED_FLOAT_OPERATION
} SCRIPT_ENGINE_ERROR_TYPE,
    *PSCRIPT_ENGINE_ERROR_TYPE;

VOID
InitializeTypeContext(VOID);

VOID
UninitializeTypeContext(VOID);

PVARIABLE_TYPE
FindStructType(const char * TagName);

PVARIABLE_TYPE
DeclareStructType(const char * TagName);

BOOLEAN
CompleteStructType(PVARIABLE_TYPE StructType);

BOOLEAN
AddStructMember(PVARIABLE_TYPE StructType, const char * Name, PVARIABLE_TYPE MemberType);

PSTRUCT_MEMBER
FindStructMember(PVARIABLE_TYPE StructType, const char * Name);

PVARIABLE_TYPE
CreatePointerType(PVARIABLE_TYPE BaseType);

PVARIABLE_TYPE
CreateArrayType(PVARIABLE_TYPE BaseType, unsigned int ArrayLength);

BOOLEAN
AddTypedefType(const char * Name, PVARIABLE_TYPE Type);

PVARIABLE_TYPE
FindTypedefType(const char * Name);

PVARIABLE_TYPE
GetDefaultImplicitVariableType(VOID);

BOOLEAN
IsIntegerVariableType(PVARIABLE_TYPE Type);

PVARIABLE_TYPE
PromoteIntegerVariableType(PVARIABLE_TYPE Type);

PVARIABLE_TYPE
GetCommonVariableType(PVARIABLE_TYPE LeftType, PVARIABLE_TYPE RightType);

#endif
