name: vs2026-ci

on:
  workflow_dispatch:

# Disabled, uncomment the below line and remove the above lines to activate  
#on:
#  push:
#    branches:
#      - master
#      - dev
#    tags:
#      - 'v*'
#    paths-ignore:
#      - '.gitignore'
#      - '.gitattributes'
#      - '**.cmd'
#      - '**.bat'
#      - '**.md'
#
#  pull_request:
#    paths-ignore:
#      - '.gitignore'
#      - '.gitattributes'
#      - '**.cmd'
#      - '**.bat'
#      - '**.md'

env:
  # Updated WDK URL for VS 2026
  SDK_URL: https://go.microsoft.com/fwlink/?linkid=2361309
  WDK_URL: https://go.microsoft.com/fwlink/?LinkId=2362091

  SOLUTION_FILE_PATH: ./hyperdbg/hyperdbg.sln
  RELEASE_ZIP_FILE_NAME: hyperdbg
  BUILD_BIN_DIR: ./hyperdbg/build/bin/

jobs:
  win-amd64-build:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
        BUILD_CONFIGURATION: [release, debug]
        PLATFORM: [x64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Checkout submodules recursively
      run: git submodule update --init --recursive --remote

    - name: Setup SDK for VS 2026
      run: |
        $sdkSetupPath = "$Env:TEMP\sdksetup.exe"
        (New-Object Net.WebClient).DownloadFile('${{env.SDK_URL}}', $sdkSetupPath)
        Start-Process -FilePath $sdkSetupPath -ArgumentList "/quiet" -NoNewWindow -Wait

    - name: Setup WDK for VS 2026
      run: |
        $wdkSetupPath = "$Env:TEMP\wdksetup.exe"
        (New-Object Net.WebClient).DownloadFile('${{env.WDK_URL}}', $wdkSetupPath)
        Start-Process -FilePath $wdkSetupPath -ArgumentList "/quiet" -NoNewWindow -Wait

    - name: List SDK folders 1
      shell: pwsh
      run: |
        Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\Include"

    - name: List SDK folders 2
      shell: pwsh
      run: |
        Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\Include\10.0.28000.0"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Build HyperDbg solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.PLATFORM}} /p:EnableInfVerif=false /p:EnableDriverApiValidation=false ${{env.SOLUTION_FILE_PATH}}

    - name: Upload build directory
      uses: actions/upload-artifact@v4.4.0
      with:
        name: build_files_${{matrix.BUILD_CONFIGURATION}}
        path: ${{ env.BUILD_BIN_DIR }}

  deploy-release:
    name: Deploy release
    needs: win-amd64-build
    runs-on: windows-2025-vs2026
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download build files from "build" job
        uses: actions/download-artifact@v4.1.7
        with:
          name: build_files_release
          path: ${{ env.BUILD_BIN_DIR }}

      - name: Archive release
        uses: thedoctor0/zip-release@master
        with:
          path: ${{ env.BUILD_BIN_DIR }}release/
          type: 'zip'
          filename: ${{env.RELEASE_ZIP_FILE_NAME}}-${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{env.RELEASE_ZIP_FILE_NAME}}-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
